// diffusion_train.cpp -- the stretch goal: a diffusion model on 2D toy
// data (spiral / two-moons), generated by Teammate B.
//
// Trains an MLP denoiser to predict noise (MSE objective), then runs the
// iterative reverse-sampling loop and checks qualitatively whether noise
// becomes structure. No new engine ops -- same matmul/add/ReLU as the GNN.
//
// Week 3 go/no-go checkpoint decides whether this gets full time or gets
// compressed/replaced by the autoencoder fallback (see app/autoencoder.cpp,
// created only if needed).

#include "microtorch/Tensor.hpp"

int main() {
    // TODO: noise schedule, denoiser training loop, reverse sampling.
    return 0;
}
